### ISSUE TITLE
Update the repo to Tabt API 0.7.16

### ISSUE THREAD

**Issue by Fllorent0D** [gfrenoy/TabT-API#1]
Hi! I wrote an app ([Beping](https://www.facebook.com/getbeping)) on mobile that make use of your API 
I want to implement tournament in my app but the documentation is not up to date. Can you help me figuring it out?

**Comment by gfrenoy** [comment]
Hello Florent!

7 years after the first publication, I'm so happy to see we finally got our issue #1 open :smile:

The most up-to-date documentation can be found here : http://api.frenoy.net/ but it's been a while since I did not update it, indeed !  I'll try to do it along with a refresh of this repository.  But don't hold you breath, it's not the highest priority today...

In the meantime, the easiest way to understand what's in there is to look at the WSDL file that is online.  If you look at the Response and Request structures, it should be fairly self-explanatory.

**Comment by Fllorent0D** [comment]
Hehe I'm glad to be the first one to open an issue. I think there aren't a lot of people using a table tennis api every day ^^

Indeed my problem is with the tournaments. I already took a look at the WSDL file and try some requests to see what I get back but It seems that I can only see a list of tournaments. My goal is to be able to see everything from a tournament.

**Comment by gfrenoy** [comment]
Well, "everything" is a bit vague.  And in any case, it looks like a separate issue.

**Comment by Fllorent0D** [comment]
I can understand that it's a bit vague ^^

Indeed, I tried to resquest the tournament and I got this : <img width="517" alt="capture d ecran 2018-04-25 a 21 49 45" src="https://user-images.githubusercontent.com/13313104/39269294-c31a381c-48d2-11e8-9807-9440995a445b.png">

I tried to check the code in the `tabtapi.php`, fork the project and send a pull request... but I could find the code of the tournaments. So I assumed that the repo is not up to date. If you could update this repo with the code online, we could fix that together.

**Comment by gfrenoy** [comment]
Hi Florent.  Yes, this issue is clear ; I'll update the code whenever possible (likely next week).

But I'm not sure the code will give you much more information than what you see in the response and what is described in the WSDL.

If you have any specific question about what is returned by GetTournaments, don't hesitate to open an new issue.
