### ISSUE TITLE
Position & RankingIndex not correct when A ranking in the list

### ISSUE THREAD

**Issue by Fllorent0D** [gfrenoy/TabT-API#10]
When there is player with A ranking in the list all the 'Position' is shifted by the number of A. Don't know if it's normal

<img width="537" alt="capture d ecran 2018-09-26 a 07 45 58" src="https://user-images.githubusercontent.com/13313104/46059667-76dcc080-c160-11e8-9b42-2f63bdfa1565.png">

**Comment by gfrenoy** [comment]
Looks correct to me ; members that are registered as "Super Division" players (status "S" or "T") do not have a index number.

If can of doubt, you can always check the list on the website and see if it matches:
   https://resultats.aftt.be/club/L264/membres

**Comment by Fllorent0D** [comment]
Junius Jonathan which is 4/3 is normal ?

**Comment by gfrenoy** [comment]
Yes.

- 4th player of the returned member list (you should actually not show that number)
- index #3 on the so called "liste des forces" (as defined by the sport rules - see C.21 of http://www.frbtt.be/wp-content/uploads/2018/08/RS-01072018.pdf)

**Comment by Fllorent0D** [comment]
If you follow S.3.4, first three players when there are playing in Super shouldn't appear in the "liste des forces".
Then it should look like this
![unknown](https://user-images.githubusercontent.com/13313104/46171111-e86f5880-c29f-11e8-8599-96a561be14ab.png)

**Comment by gfrenoy** [comment]
And there are not since "RankingIndex" is 0...

Please understand that "[GetMembers](http://api.frenoy.net/group__TabTAPIfunctions.html#ga7f0afb557750e332b30110a17dea9e9c)" gives you the list of members of the club ; not the so called "liste des forces".

It's up to you to build it according to the Status (must be A or V ; or T or S for Super Division) and possibly the RankingPosition (that is 0 for members with status T and S so this is redundant with the status).
