### ISSUE TITLE
GetTournaments : MatchEntry missing

### ISSUE THREAD

**Issue by Fllorent0D** [gfrenoy/TabT-API#2]
GetTournaments only send back tournament entries and the series of each tournament. We should get an option to get the match entries of a tournament. 

<img width="517" alt="capture d ecran 2018-04-25 a 21 49 45" src="https://user-images.githubusercontent.com/13313104/39467224-44cbe6fe-4d2d-11e8-87f8-d4585ea2e399.png">

**Comment by gfrenoy** [comment]
Yes, that certainly makes sense.  I would restrict that to only one tournament to start with.  So we would also need a parameter to select the tournament.

**Comment by Fllorent0D** [comment]
Look perfect to me if you do that! So, I can query once the GetTournament and then query again with the new parameter when the user wants to see the details.

**Comment by Fllorent0D** [comment]
@gfrenoy Any updates? 😅

**Comment by gfrenoy** [comment]
@Fllorent0D Any suggestion on how should look the new GetTournamentsRequest and GetTournamentsResponse ?

**Comment by Fonsvanh** [comment]
Dear all,

I’ve followed this discussion in the background.  I use the TABT-API in an Excel vba macro to produce a weekly overview of the match result.

This overview is published in our provincial monthly magazine.

Recently I’ve started developing a vb.net program using the TABT-API to check whether the interclub regulations have been violated and to sanction the clubs for this. Today this is done manually but this can be done programmatically.

This program is not finished yet but it’s my intention to finish it by the start of next season.

I also like to use the API to publish the tournament results in my monthly because I’m not happy with the layout of the results I receive today (word documents)

What data is stored in the database regarding the tournaments?

Krgds,

Alfons Vanhoudt
Secretaris PCLK

**Comment by gfrenoy** [comment]
Thanks for your feedback Alfons :)  Happy to read the API is used in ways that were certainly not foreseen in the beginning !

In the TabT database, you have only a "flat" list of results for each series, like this:
   https://competitie.vttl.be/?menu=7&viewresults=1&t_id=2641

There is no clue about the structure of the tournament.  So you don't have the necessary information to rebuild the final round table and/or round robin tables.

That being said, this information is for sure kept in the database of the tournament application so we should check with Luc how to transfer this in text files that are exported from that application (and then imported in TabT).

**Comment by Fllorent0D** [comment]
Sorry for the late response. 
I don't know how the tournaments works in real world. If it's always the same flows: pools, quarter-final, semi-final, final, ... If it's always the same we can create a object in each SerieEntries with in it 
```
{
  pools:[MatchEntryDetails],
  quarter-final:[MatchEntryDetails],
  semi-final: [MatchEntryDetails],
  final: atchEntryDetails,
}
```  

What do you think?

**Comment by gfrenoy** [comment]
As said in the [previous comment](https://github.com/gfrenoy/TabT-API/issues/2#issuecomment-388947275), there is no information about the structure of the tournament in the database.  It's just a flat list of results.

Anyway, at this stage, the first step to complete this request is to change the [WSDL](https://github.com/gfrenoy/TabT-API/blob/master/tabt.wsdl) file.  And especially the ````GetTournaments_Request```` and ````GetTournaments_Response```` structures.
